"""
Django settings for oobapigw project.

Generated by 'django-admin startproject' using Django 2.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""
from __future__ import unicode_literals
from os.path import abspath, basename, dirname, join, normpath
from sys import path


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = dirname(dirname(abspath(__file__)))
DJANGO_ROOT = dirname(dirname(abspath(__file__)))
SITE_ROOT = dirname(DJANGO_ROOT)
SITE_NAME = "API_OOB"
path.append(DJANGO_ROOT)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '2zrr-w4=*z^&q4$&%=h!3h#y(^)k7z%84a+vxdcg8w^^r&37bq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []

ADMINS = (
    ('Trung. Nguyen', 'trungn@vng.com.vn'),
)
MANAGERS = ADMINS

# Application definition

CORE_APPS = [
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

]

THIRD_PARTY_APPS = [
    'django_extensions',
    'rest_framework',
]

MY_APPS = [
    'apps.api'
]

INSTALLED_APPS = CORE_APPS + THIRD_PARTY_APPS + MY_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'middlewares.header_authentication.Checksum_Header'
]

LOGGING = {
    'version' : 1,
    'disabled_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format' :  '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style'  : '{'
        },
        'simple' : {
            'format' : '{levelname} {message}',
            'style'  : '{'
        }
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'file': {
            'level' : 'DEBUG',
            'class' : 'logging.FileHandler',
            'filename': BASE_DIR + "/django_debug.log",
            'formatter': 'simple'
        },
        'console': {
            'level': 'INFO',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'api': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR + "/logs/api.log",
            # 'maxBytes': 1024*1024*15,
            # 'backupCount': 10,
        }
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'propagate': True,
        },
        'api': {
            'handlers': ['api'],
            'level': 'INFO',
            'propagate': True
        }
    }
}

ROOT_URLCONF = 'settings.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                #'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
REST_FRAMEWORK = {
    'EXCEPTION_HANDLER' : 'services.custom_exeption_handlers.custom_exeption_handlers'
}


LOCALE_PATHS = (
    join(SITE_ROOT, 'locale'),
)

# WSGI_APPLICATION = 'oob.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'guacamole_db',
        'USER': 'guacamole_user',
        'PASSWORD': '3iDwp8PNZhiYnbLHqC2s',
        'HOST': '10.10.34.101',
        'POST': '3306'
    }
}


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = normpath(join(SITE_ROOT, 'static'))
STATICFILES_DIRS = (
    normpath(join(SITE_ROOT, 'static')),
)
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)
APPEND_SLASH  = True


####
#For API incomming
####
USER_API = "t0s4ser"
PASS_API = "c353979018923f2b5eaa350f05e77b2f"
